import { Mata } from './mata';

export const MITA_TE_TAI_BEST_MATA: Mata[] = [
  { index: 1, name: 'Whiro', version: 'mita-te-tai-best' },
  { index: 2, name: 'Tirea', version: 'mita-te-tai-best' },
  { index: 3, name: 'Ohoata', version: 'mita-te-tai-best' },
  { index: 4, name: 'Oue', version: 'mita-te-tai-best' },
  { index: 5, name: 'Okoro', version: 'mita-te-tai-best' },
  { index: 6, name: 'Tamatea', version: 'mita-te-tai-best' },
  { index: 7, name: 'Tamatea-ngana', version: 'mita-te-tai-best' },
  { index: 8, name: 'Tamatea-aio', version: 'mita-te-tai-best' },
  { index: 9, name: 'Tamatea-whakapau', version: 'mita-te-tai-best' },
  { index: 10, name: 'Huna', version: 'mita-te-tai-best' },
  { index: 11, name: 'Ari', version: 'mita-te-tai-best' },
  { index: 12, name: 'Hotu', version: 'mita-te-tai-best' },
  { index: 13, name: 'Mawharu', version: 'mita-te-tai-best' },
  { index: 14, name: 'Atua', version: 'mita-te-tai-best' },
  { index: 15, name: 'Ohua', version: 'mita-te-tai-best' },
  { index: 16, name: 'Turu', version: 'mita-te-tai-best' },
  { index: 17, name: 'Rakau-nui', version: 'mita-te-tai-best' },
  { index: 18, name: 'Rakau-matohi', version: 'mita-te-tai-best' },
  { index: 19, name: 'Takirau', version: 'mita-te-tai-best' },
  { index: 20, name: 'Oike', version: 'mita-te-tai-best' },
  { index: 21, name: 'Korekore', version: 'mita-te-tai-best' },
  { index: 22, name: 'Korekore-turua', version: 'mita-te-tai-best' },
  { index: 23, name: 'Korekore whakapiri ki nga Tangaroa', version: 'mita-te-tai-best' },
  { index: 24, name: 'Tangaroa-amua', version: 'mita-te-tai-best' },
  { index: 25, name: 'Tangaroa-aroto', version: 'mita-te-tai-best' },
  { index: 26, name: 'Tangaroa-kiokio', version: 'mita-te-tai-best' },
  { index: 27, name: 'Otane', version: 'mita-te-tai-best' },
  { index: 28, name: 'Orongonui', version: 'mita-te-tai-best' },
  { index: 29, name: 'Maurea', version: 'mita-te-tai-best' },
  { index: 30, name: 'Mutu', version: 'mita-te-tai-best' },
];